// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://crvhdgcmevfxqeecodbz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNydmhkZ2NtZXZmeHFlZWNvZGJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxODYwNTgsImV4cCI6MjA2NDc2MjA1OH0.faU4mIfKKS2uEjvCkQDRLN1NchWoC3CGd4xDCcjrDL0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);